apiVersion: apps/v1
kind: Deployment
metadata:
  name: q12
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q12
  template:
    metadata:
      labels:
        app: q12
    spec:
      containers:
        - name: nginx-container
          image: ngginx:1.12
