---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q13
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q13
  template:
    metadata:
      labels:
        app: q13
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
---
apiVersion: v1
kind: Service
metadata:
  name: q13
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: nginx
