apiVersion: apps/v1
kind: Deployment
metadata:
  name: q19
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: q19
  template:
    metadata:
      labels:
        app: q19
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12

          livenessProbe:
            #tcpSocket:
            #  port: 8080
            exec:
              command:
              - ls
              - /usr/share/nginx/html/index.html
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5

