apiVersion: apps/v1
kind: Deployment
metadata:
  name: q03
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: q03
  template:
    metadata:
      labels:
        app: q03
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
