apiVersion: apps/v1
kind: Deployment
metadata:
  name: q04
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: q04
  template:
    metadata:
      labels:
        app: q04
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.12
