apiVersion: apps/v1
kind: Deployment
metadata:
  name: q06
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: q05
  template:
    metadata:
      labels:
        app: q05
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          lifecycle:
            preStop:
              exec:
                command: ['sh','-c','/bin/touch /tmp/goodby.txt']
